[project]
name = "spa-comments"
version = "0.1.0"
description = "SPA comments test task: Django + DRF + Channels + Vue 3"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bleach>=6.4.0",
    "celery>=5.6.3",
    "channels-redis>=4.3.0",
    "channels[daphne]>=4.1",
    "django>=5.1,<6.0",
    "django-filter>=24.2",
    "django-mptt>=0.16",
    "django-redis>=7.0.0",
    "django-simple-captcha>=0.7.0",
    "djangorestframework>=3.15",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "pillow>=10.4",
    "psycopg[binary]>=3.1",
    "redis>=8.1.0",
    "whitenoise>=6.6",
]
