# Generated by Django 5.2.17 on 2026-09-24 15:28

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('home_page', models.URLField(blank=True, default='', max_length=500)),
                ('text', models.TextField(help_text='Sanitized XHTML with allowed tags only')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/')),
                ('text_file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', '-created_at'], name='comments_co_parent__2efacb_idx'), models.Index(fields=['tree_id', 'lft'], name='comments_comment_tree_id_l4b1c')],
            },
        ),
    ]
