-- =====================================================================
-- SPA Comments — PostgreSQL schema (authoritative DDL, taken from
-- `manage.py sqlmigrate`). The ONLY database in this project is PostgreSQL.
--
-- Tables designed for this project:
--   1. comments_comment      — comments tree (django-mptt nested sets)
--   2. captcha_captchastore  — django-simple-captcha challenge store
--      (third-party package table, shown for completeness)
--
-- Mirrors: backend/apps/comments/migrations/0001_initial.py
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Comments tree.
-- Top-level comments are nodes with parent_id IS NULL (MPTT level = 0).
-- Replies nest infinitely via the self-referencing parent FK (MPTT
-- maintains lft/rght/tree_id/level automatically on save).
-- Author snapshot (user_name/email) is copied from the JWT profile at
-- post time, so later profile edits never rewrite history.
-- ---------------------------------------------------------------------
CREATE TABLE "comments_comment" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_name" varchar(50) NOT NULL,
    "email" varchar(254) NOT NULL,
    "home_page" varchar(500) NOT NULL,
    "text" text NOT NULL,
    "image" varchar(100) NULL,
    "text_file" varchar(100) NULL,
    "created_at" timestamptz NOT NULL,
    "lft" integer NOT NULL CHECK ("lft" >= 0),
    "rght" integer NOT NULL CHECK ("rght" >= 0),
    "tree_id" integer NOT NULL CHECK ("tree_id" >= 0),
    "level" integer NOT NULL CHECK ("level" >= 0),
    "parent_id" bigint NULL
);
ALTER TABLE "comments_comment"
    ADD CONSTRAINT "comments_comment_parent_id_3e0802fb_fk_comments_comment_id"
    FOREIGN KEY ("parent_id") REFERENCES "comments_comment" ("id")
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "comments_comment_user_name_7c141bff"
    ON "comments_comment" ("user_name");
CREATE INDEX "comments_comment_email_eb098ebd"
    ON "comments_comment" ("email");
CREATE INDEX "comments_comment_created_at_c684ddb5"
    ON "comments_comment" ("created_at");
CREATE INDEX "comments_comment_tree_id_d91ce17d"
    ON "comments_comment" ("tree_id");
CREATE INDEX "comments_co_parent__2efacb_idx"
    ON "comments_comment" ("parent_id", "created_at" DESC);
CREATE INDEX "comments_comment_tree_id_l4b1c"
    ON "comments_comment" ("tree_id", "lft");

-- ---------------------------------------------------------------------
-- 2. CAPTCHA challenge store (django-simple-captcha).
-- One row per issued challenge; deleted on first verification attempt
-- (one-time use) or swept when expired, so the table never grows forever.
-- ---------------------------------------------------------------------
CREATE TABLE "captcha_captchastore" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "challenge" varchar(32) NOT NULL,
    "response" varchar(32) NOT NULL,
    "hashkey" varchar(40) NOT NULL UNIQUE,
    "expiration" timestamptz NOT NULL
);

COMMIT;
