-- =====================================================================
-- SPA Comments — PostgreSQL schema (authoritative DDL, taken from
-- `manage.py sqlmigrate`). The ONLY database in this project is PostgreSQL.
--
-- Tables included in this schema:
--   project tables: comments_comment, captcha_captchastore
--   framework tables: auth_*, django_content_type, django_migrations,
--                     django_admin_log, django_session
--
-- Mirrors: backend/apps/comments/migrations/0001_initial.py
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Comments tree.
-- Top-level comments are nodes with parent_id IS NULL (MPTT level = 0).
-- Replies nest infinitely via the self-referencing parent FK (MPTT
-- maintains lft/rght/tree_id/level automatically on save).
-- Author snapshot (user_name/email) is copied from the JWT profile at
-- post time, so later profile edits never rewrite history.
-- ---------------------------------------------------------------------
CREATE TABLE "comments_comment" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_name" varchar(50) NOT NULL,
    "email" varchar(254) NOT NULL,
    "home_page" varchar(500) NOT NULL,
    "text" text NOT NULL,
    "image" varchar(100) NULL,
    "text_file" varchar(100) NULL,
    "created_at" timestamptz NOT NULL,
    "lft" integer NOT NULL CHECK ("lft" >= 0),
    "rght" integer NOT NULL CHECK ("rght" >= 0),
    "tree_id" integer NOT NULL CHECK ("tree_id" >= 0),
    "level" integer NOT NULL CHECK ("level" >= 0),
    "parent_id" bigint NULL
);
ALTER TABLE "comments_comment"
    ADD CONSTRAINT "comments_comment_parent_id_3e0802fb_fk_comments_comment_id"
    FOREIGN KEY ("parent_id") REFERENCES "comments_comment" ("id")
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "comments_comment_user_name_7c141bff"
    ON "comments_comment" ("user_name");
CREATE INDEX "comments_comment_email_eb098ebd"
    ON "comments_comment" ("email");
CREATE INDEX "comments_comment_created_at_c684ddb5"
    ON "comments_comment" ("created_at");
CREATE INDEX "comments_comment_tree_id_d91ce17d"
    ON "comments_comment" ("tree_id");
CREATE INDEX "comments_co_parent__2efacb_idx"
    ON "comments_comment" ("parent_id", "created_at" DESC);
CREATE INDEX "comments_comment_tree_id_l4b1c"
    ON "comments_comment" ("tree_id", "lft");

-- ---------------------------------------------------------------------
-- 2. CAPTCHA challenge store (django-simple-captcha).
-- One row per issued challenge; deleted on first verification attempt
-- (one-time use) or swept when expired, so the table never grows forever.
-- ---------------------------------------------------------------------
CREATE TABLE "captcha_captchastore" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "challenge" varchar(32) NOT NULL,
    "response" varchar(32) NOT NULL,
    "hashkey" varchar(40) NOT NULL UNIQUE,
    "expiration" timestamptz NOT NULL
);

-- ---------------------------------------------------------------------
-- 3. Django content types and migrations.
-- These are framework tables used by permissions, admin and migration
-- tracking and are part of the deployed database.
-- ---------------------------------------------------------------------
CREATE TABLE "django_content_type" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "app_label" varchar(100) NOT NULL,
    "model" varchar(100) NOT NULL,
    CONSTRAINT "django_content_type_app_label_model_uniq"
        UNIQUE ("app_label", "model")
);

CREATE TABLE "django_migrations" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "app" varchar(255) NOT NULL,
    "name" varchar(255) NOT NULL,
    "applied" timestamptz NOT NULL
);

-- ---------------------------------------------------------------------
-- 4. Django authentication and authorization.
-- JWT authenticates these users; comments intentionally keep an author
-- snapshot and therefore do not have a foreign key to auth_user.
-- ---------------------------------------------------------------------
CREATE TABLE "auth_group" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(150) NOT NULL UNIQUE
);

CREATE TABLE "auth_permission" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" varchar(100) NOT NULL,
    CONSTRAINT "auth_permission_content_type_codename_uniq"
        UNIQUE ("content_type_id", "codename"),
    CONSTRAINT "auth_permission_content_type_fk"
        FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id")
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "auth_user" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "password" varchar(128) NOT NULL,
    "last_login" timestamptz NULL,
    "is_superuser" boolean NOT NULL,
    "username" varchar(150) NOT NULL UNIQUE,
    "first_name" varchar(150) NOT NULL,
    "last_name" varchar(150) NOT NULL,
    "email" varchar(254) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamptz NOT NULL
);

CREATE TABLE "auth_group_permissions" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "group_id" integer NOT NULL,
    "permission_id" integer NOT NULL,
    CONSTRAINT "auth_group_permissions_uniq" UNIQUE ("group_id", "permission_id"),
    CONSTRAINT "auth_group_permissions_group_fk"
        FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id")
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "auth_group_permissions_permission_fk"
        FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id")
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "auth_user_groups" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer NOT NULL,
    "group_id" integer NOT NULL,
    CONSTRAINT "auth_user_groups_uniq" UNIQUE ("user_id", "group_id"),
    CONSTRAINT "auth_user_groups_user_fk"
        FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id")
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "auth_user_groups_group_fk"
        FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id")
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "auth_user_user_permissions" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer NOT NULL,
    "permission_id" integer NOT NULL,
    CONSTRAINT "auth_user_user_permissions_uniq" UNIQUE ("user_id", "permission_id"),
    CONSTRAINT "auth_user_user_permissions_user_fk"
        FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id")
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "auth_user_user_permissions_permission_fk"
        FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id")
        DEFERRABLE INITIALLY DEFERRED
);

-- ---------------------------------------------------------------------
-- 5. Django admin and sessions.
-- ---------------------------------------------------------------------
CREATE TABLE "django_admin_log" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "action_time" timestamptz NOT NULL,
    "object_id" text NULL,
    "object_repr" varchar(200) NOT NULL,
    "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0),
    "change_message" text NOT NULL,
    "content_type_id" integer NULL,
    "user_id" integer NOT NULL,
    CONSTRAINT "django_admin_log_content_type_fk"
        FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id")
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "django_admin_log_user_fk"
        FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id")
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "django_session" (
    "session_key" varchar(40) NOT NULL PRIMARY KEY,
    "session_data" text NOT NULL,
    "expire_date" timestamptz NOT NULL
);

CREATE INDEX "django_session_expire_date_idx"
    ON "django_session" ("expire_date");
CREATE INDEX "django_admin_log_content_type_idx"
    ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_idx"
    ON "django_admin_log" ("user_id");
CREATE INDEX "auth_permission_content_type_idx"
    ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_permissions_group_idx"
    ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_idx"
    ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_user_groups_user_idx"
    ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_idx"
    ON "auth_user_groups" ("group_id");
CREATE INDEX "auth_user_user_permissions_user_idx"
    ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_idx"
    ON "auth_user_user_permissions" ("permission_id");

COMMIT;
